server:
  port: 5527

spring:
  application:
    name: job
  datasource:
    url: jdbc:mysql:///cloud?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    hikari:
      max-lifetime: 360000
  jpa:
    hibernate:
      ddl-auto: update
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
